package com.taobao.cun.auge.dal.mapper;


import com.taobao.cun.auge.dal.domain.AddressInfoDecision;
import com.taobao.cun.auge.dal.domain.AddressInfoDecisionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AddressInfoDecisionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    int countByExample(AddressInfoDecisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    int deleteByExample(AddressInfoDecisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    int insert(AddressInfoDecision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    int insertSelective(AddressInfoDecision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    List<AddressInfoDecision> selectByExample(AddressInfoDecisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    AddressInfoDecision selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") AddressInfoDecision record, @Param("example") AddressInfoDecisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    int updateByExample(@Param("record") AddressInfoDecision record, @Param("example") AddressInfoDecisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    int updateByPrimaryKeySelective(AddressInfoDecision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info_decision
     *
     * @mbggenerated Thu Apr 26 15:54:57 CST 2018
     */
    int updateByPrimaryKey(AddressInfoDecision record);
}