package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.CountyStation;
import com.taobao.cun.auge.dal.domain.CountyStationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountyStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int countByExample(CountyStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int deleteByExample(CountyStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int insert(CountyStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int insertSelective(CountyStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    List<CountyStation> selectByExample(CountyStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    CountyStation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") CountyStation record, @Param("example") CountyStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByExample(@Param("record") CountyStation record, @Param("example") CountyStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByPrimaryKeySelective(CountyStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByPrimaryKey(CountyStation record);
}