package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.CountyStationTransferJob;
import com.taobao.cun.auge.dal.domain.CountyStationTransferJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountyStationTransferJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    int countByExample(CountyStationTransferJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    int deleteByExample(CountyStationTransferJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    int insert(CountyStationTransferJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    int insertSelective(CountyStationTransferJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    List<CountyStationTransferJob> selectByExample(CountyStationTransferJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    CountyStationTransferJob selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CountyStationTransferJob record, @Param("example") CountyStationTransferJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CountyStationTransferJob record, @Param("example") CountyStationTransferJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CountyStationTransferJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_station_transfer_job
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CountyStationTransferJob record);
}