package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.CuntaoFlowRecord;
import com.taobao.cun.auge.dal.domain.CuntaoFlowRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuntaoFlowRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int countByExample(CuntaoFlowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int deleteByExample(CuntaoFlowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int insert(CuntaoFlowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int insertSelective(CuntaoFlowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    List<CuntaoFlowRecord> selectByExample(CuntaoFlowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    CuntaoFlowRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") CuntaoFlowRecord record, @Param("example") CuntaoFlowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByExample(@Param("record") CuntaoFlowRecord record, @Param("example") CuntaoFlowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByPrimaryKeySelective(CuntaoFlowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_flow_record
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByPrimaryKey(CuntaoFlowRecord record);
}