package com.taobao.cun.auge.dal.mapper;

import java.util.List;

import com.taobao.cun.auge.dal.domain.CuntaoAssetFlowDetail;
import com.taobao.cun.auge.dal.domain.CuntaoAssetFlowDetailExample;
import org.apache.ibatis.annotations.Param;

public interface CuntaoAssetFlowDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    int countByExample(CuntaoAssetFlowDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    int deleteByExample(CuntaoAssetFlowDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    int insert(CuntaoAssetFlowDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    int insertSelective(CuntaoAssetFlowDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    List<CuntaoAssetFlowDetail> selectByExample(CuntaoAssetFlowDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    CuntaoAssetFlowDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CuntaoAssetFlowDetail record, @Param("example") CuntaoAssetFlowDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CuntaoAssetFlowDetail record, @Param("example") CuntaoAssetFlowDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CuntaoAssetFlowDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_asset_flow_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CuntaoAssetFlowDetail record);
}