package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.CuntaoCountyGovProtocol;
import com.taobao.cun.auge.dal.domain.CuntaoCountyGovProtocolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuntaoCountyGovProtocolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    int countByExample(CuntaoCountyGovProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    int deleteByExample(CuntaoCountyGovProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    int insert(CuntaoCountyGovProtocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    int insertSelective(CuntaoCountyGovProtocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    List<CuntaoCountyGovProtocol> selectByExample(CuntaoCountyGovProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    CuntaoCountyGovProtocol selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CuntaoCountyGovProtocol record, @Param("example") CuntaoCountyGovProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CuntaoCountyGovProtocol record, @Param("example") CuntaoCountyGovProtocolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CuntaoCountyGovProtocol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_county_gov_protocol
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CuntaoCountyGovProtocol record);
}