package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.CuntaoQualification;
import com.taobao.cun.auge.dal.domain.CuntaoQualificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuntaoQualificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    int countByExample(CuntaoQualificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    int deleteByExample(CuntaoQualificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    int insert(CuntaoQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    int insertSelective(CuntaoQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    List<CuntaoQualification> selectByExample(CuntaoQualificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    CuntaoQualification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CuntaoQualification record, @Param("example") CuntaoQualificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CuntaoQualification record, @Param("example") CuntaoQualificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CuntaoQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_qualification
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CuntaoQualification record);
}