package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.CuntaoCompanyEmployee;
import com.taobao.cun.auge.dal.domain.CuntaoCompanyEmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuntaoCompanyEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    int countByExample(CuntaoCompanyEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    int deleteByExample(CuntaoCompanyEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    int insert(CuntaoCompanyEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    int insertSelective(CuntaoCompanyEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    List<CuntaoCompanyEmployee> selectByExample(CuntaoCompanyEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    CuntaoCompanyEmployee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CuntaoCompanyEmployee record, @Param("example") CuntaoCompanyEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CuntaoCompanyEmployee record, @Param("example") CuntaoCompanyEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CuntaoCompanyEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuntao_company_employee
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CuntaoCompanyEmployee record);
}