package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.DwiCtStationTpaD;
import com.taobao.cun.auge.dal.domain.DwiCtStationTpaDExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DwiCtStationTpaDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    int countByExample(DwiCtStationTpaDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    int deleteByExample(DwiCtStationTpaDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    int insert(DwiCtStationTpaD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    int insertSelective(DwiCtStationTpaD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    List<DwiCtStationTpaD> selectByExample(DwiCtStationTpaDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    DwiCtStationTpaD selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DwiCtStationTpaD record, @Param("example") DwiCtStationTpaDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DwiCtStationTpaD record, @Param("example") DwiCtStationTpaDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DwiCtStationTpaD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwi_ct_station_tpa_d
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DwiCtStationTpaD record);
}