package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.LogisticsStationApply;
import com.taobao.cun.auge.dal.domain.LogisticsStationApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogisticsStationApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int countByExample(LogisticsStationApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int deleteByExample(LogisticsStationApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int insert(LogisticsStationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int insertSelective(LogisticsStationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    List<LogisticsStationApply> selectByExample(LogisticsStationApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    LogisticsStationApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") LogisticsStationApply record, @Param("example") LogisticsStationApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByExample(@Param("record") LogisticsStationApply record, @Param("example") LogisticsStationApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByPrimaryKeySelective(LogisticsStationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByPrimaryKey(LogisticsStationApply record);
}