package com.taobao.cun.auge.dal.mapper;

import java.util.List;

import com.taobao.cun.auge.dal.domain.PartnerInstanceExt;
import com.taobao.cun.auge.dal.domain.PartnerInstanceExtExample;
import org.apache.ibatis.annotations.Param;

public interface PartnerInstanceExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    int countByExample(PartnerInstanceExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    int deleteByExample(PartnerInstanceExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    int insert(PartnerInstanceExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    int insertSelective(PartnerInstanceExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    List<PartnerInstanceExt> selectByExample(PartnerInstanceExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    PartnerInstanceExt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") PartnerInstanceExt record, @Param("example") PartnerInstanceExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    int updateByExample(@Param("record") PartnerInstanceExt record, @Param("example") PartnerInstanceExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(PartnerInstanceExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_ext
     *
     * @mbggenerated Mon Jul 18 17:59:12 GMT+08:00 2016
     */
    int updateByPrimaryKey(PartnerInstanceExt record);
}