package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.PartnerMeeting;
import com.taobao.cun.auge.dal.domain.PartnerMeetingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartnerMeetingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    int countByExample(PartnerMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    int deleteByExample(PartnerMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    int insert(PartnerMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    int insertSelective(PartnerMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    List<PartnerMeeting> selectByExample(PartnerMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    PartnerMeeting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PartnerMeeting record, @Param("example") PartnerMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PartnerMeeting record, @Param("example") PartnerMeetingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PartnerMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_meeting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartnerMeeting record);
}