package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.PartnerCourseRecord;
import com.taobao.cun.auge.dal.domain.PartnerCourseRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartnerCourseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    int countByExample(PartnerCourseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    int deleteByExample(PartnerCourseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    int insert(PartnerCourseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    int insertSelective(PartnerCourseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    List<PartnerCourseRecord> selectByExample(PartnerCourseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    PartnerCourseRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") PartnerCourseRecord record, @Param("example") PartnerCourseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    int updateByExample(@Param("record") PartnerCourseRecord record, @Param("example") PartnerCourseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    int updateByPrimaryKeySelective(PartnerCourseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_course_record
     *
     * @mbggenerated Tue Jul 12 20:13:50 CST 2016
     */
    int updateByPrimaryKey(PartnerCourseRecord record);
}