package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.PartnerInsuranceDetail;
import com.taobao.cun.auge.dal.domain.PartnerInsuranceDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PartnerInsuranceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    int countByExample(PartnerInsuranceDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    int deleteByExample(PartnerInsuranceDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    int insert(PartnerInsuranceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    int insertSelective(PartnerInsuranceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    List<PartnerInsuranceDetail> selectByExample(PartnerInsuranceDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    PartnerInsuranceDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") PartnerInsuranceDetail record, @Param("example") PartnerInsuranceDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    int updateByExample(@Param("record") PartnerInsuranceDetail record, @Param("example") PartnerInsuranceDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    int updateByPrimaryKeySelective(PartnerInsuranceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_insurance_detail
     *
     * @mbggenerated Fri Feb 22 18:05:21 CST 2019
     */
    int updateByPrimaryKey(PartnerInsuranceDetail record);
}