package com.taobao.cun.auge.dal.mapper;

import java.util.List;
import java.util.Map;

import com.taobao.cun.auge.alilang.UserProfile;
import com.taobao.cun.auge.dal.domain.PartnerStationRel;
import com.taobao.cun.auge.dal.domain.PartnerStationRelExample;
import org.apache.ibatis.annotations.Param;

public interface PartnerStationRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    int countByExample(PartnerStationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    int deleteByExample(PartnerStationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    int insert(PartnerStationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    int insertSelective(PartnerStationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    List<PartnerStationRel> selectByExample(PartnerStationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    PartnerStationRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PartnerStationRel record, @Param("example") PartnerStationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PartnerStationRel record, @Param("example") PartnerStationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PartnerStationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_station_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PartnerStationRel record);
    
    List<UserProfile> queryUserProfileForAlilangMeeting(Map<String,Object> param);
    
   	List<PartnerStationRel> getInstanceForMobileJudge(Map<String, Object> param);
}