package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.PartnerInstanceLevel;
import com.taobao.cun.auge.dal.domain.PartnerInstanceLevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartnerInstanceLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    int countByExample(PartnerInstanceLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    int deleteByExample(PartnerInstanceLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    int insert(PartnerInstanceLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    int insertSelective(PartnerInstanceLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    List<PartnerInstanceLevel> selectByExample(PartnerInstanceLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    PartnerInstanceLevel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") PartnerInstanceLevel record, @Param("example") PartnerInstanceLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    int updateByExample(@Param("record") PartnerInstanceLevel record, @Param("example") PartnerInstanceLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    int updateByPrimaryKeySelective(PartnerInstanceLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_instance_level
     *
     * @mbggenerated Fri Jul 29 15:41:06 CST 2016
     */
    int updateByPrimaryKey(PartnerInstanceLevel record);
}