package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.StationApply;
import com.taobao.cun.auge.dal.domain.StationApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StationApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int countByExample(StationApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int deleteByExample(StationApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int insert(StationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int insertSelective(StationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    List<StationApply> selectByExample(StationApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    StationApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") StationApply record, @Param("example") StationApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByExample(@Param("record") StationApply record, @Param("example") StationApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByPrimaryKeySelective(StationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_apply
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    int updateByPrimaryKey(StationApply record);
}