package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.StationNewCustomer;
import com.taobao.cun.auge.dal.domain.StationNewCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StationNewCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    int countByExample(StationNewCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    int deleteByExample(StationNewCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    int insert(StationNewCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    int insertSelective(StationNewCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    List<StationNewCustomer> selectByExample(StationNewCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    StationNewCustomer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StationNewCustomer record, @Param("example") StationNewCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StationNewCustomer record, @Param("example") StationNewCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationNewCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_new_customer_0000
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationNewCustomer record);
}