package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.StationTransInfo;
import com.taobao.cun.auge.dal.domain.StationTransInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StationTransInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_trans_info
     *
     * @mbggenerated
     */
    int deleteByExample(StationTransInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_trans_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_trans_info
     *
     * @mbggenerated
     */
    int insert(StationTransInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_trans_info
     *
     * @mbggenerated
     */
    int insertSelective(StationTransInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_trans_info
     *
     * @mbggenerated
     */
    List<StationTransInfo> selectByExample(StationTransInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_trans_info
     *
     * @mbggenerated
     */
    StationTransInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_trans_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StationTransInfo record, @Param("example") StationTransInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_trans_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StationTransInfo record, @Param("example") StationTransInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_trans_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationTransInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_trans_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationTransInfo record);
}