package com.taobao.cun.auge.dal.mapper;

import java.util.List;

import com.taobao.cun.auge.dal.domain.StationModifyApply;
import com.taobao.cun.auge.dal.domain.StationModifyApplyExample;
import org.apache.ibatis.annotations.Param;

public interface StationModifyApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    int countByExample(StationModifyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    int deleteByExample(StationModifyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    int insert(StationModifyApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    int insertSelective(StationModifyApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    List<StationModifyApply> selectByExample(StationModifyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    StationModifyApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StationModifyApply record, @Param("example") StationModifyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StationModifyApply record, @Param("example") StationModifyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationModifyApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_modify_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationModifyApply record);
}