package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.StoreCreateError;
import com.taobao.cun.auge.dal.domain.StoreCreateErrorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreCreateErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    int countByExample(StoreCreateErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    int deleteByExample(StoreCreateErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    int insert(StoreCreateError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    int insertSelective(StoreCreateError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    List<StoreCreateError> selectByExample(StoreCreateErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    StoreCreateError selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StoreCreateError record, @Param("example") StoreCreateErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StoreCreateError record, @Param("example") StoreCreateErrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StoreCreateError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_create_error
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StoreCreateError record);
}