package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.TownLevelAlterApply;
import com.taobao.cun.auge.dal.domain.TownLevelAlterApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TownLevelAlterApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    int countByExample(TownLevelAlterApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    int deleteByExample(TownLevelAlterApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    int insert(TownLevelAlterApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    int insertSelective(TownLevelAlterApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    List<TownLevelAlterApply> selectByExample(TownLevelAlterApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    TownLevelAlterApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TownLevelAlterApply record, @Param("example") TownLevelAlterApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TownLevelAlterApply record, @Param("example") TownLevelAlterApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TownLevelAlterApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town_level_alter_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TownLevelAlterApply record);
}