package com.taobao.cun.auge.dal.mapper;

import com.taobao.cun.auge.dal.domain.UserFilterRule;
import com.taobao.cun.auge.dal.domain.UserFilterRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFilterRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    int countByExample(UserFilterRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    int deleteByExample(UserFilterRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    int insert(UserFilterRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    int insertSelective(UserFilterRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    List<UserFilterRule> selectByExample(UserFilterRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    UserFilterRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserFilterRule record, @Param("example") UserFilterRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserFilterRule record, @Param("example") UserFilterRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserFilterRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_filter_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserFilterRule record);
}