FROM reg.docker.alibaba-inc.com/aone-base-global/xls7u_base:1.0.4

RUN sed -i '$i\sed -i "s\/180\/360\/g" /home/admin/${APP_NAME}/bin/preload.sh' /home/admin/start.sh
RUN sed -i '$i\sed -i "s\/MetaspaceSize=256m -XX:MaxMetaspaceSize=256m\/MetaspaceSize=512m -XX:MaxMetaspaceSize=512m\/g" /home/admin/${APP_NAME}/bin/setenv.sh' /home/admin/start.sh

COPY ${APP_NAME}.tgz /home/admin/${APP_NAME}/target/${APP_NAME}.tgz