FROM reg.docker.alibaba-inc.com/aone-base-global/xls7u_base:1.0.3

RUN sed -i '$i\sed -i "s\/180\/360\/g" /home/admin/${APP_NAME}/bin/preload.sh;sed -i "s\/256\/512\/g" /home/admin/${APP_NAME}/bin/setenv.sh' /home/admin/start.sh

COPY ${APP_NAME}.tgz /home/admin/${APP_NAME}/target/${APP_NAME}.tgz