package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class AppBizLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_log.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_log.biz_type
     *
     * @mbggenerated
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_log.biz_key
     *
     * @mbggenerated
     */
    private Long bizKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_log.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_log.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_log.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_log.id
     *
     * @return the value of app_biz_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_log.id
     *
     * @param id the value for app_biz_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_log.gmt_create
     *
     * @return the value of app_biz_log.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_log.gmt_create
     *
     * @param gmtCreate the value for app_biz_log.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_log.biz_type
     *
     * @return the value of app_biz_log.biz_type
     *
     * @mbggenerated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_log.biz_type
     *
     * @param bizType the value for app_biz_log.biz_type
     *
     * @mbggenerated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_log.biz_key
     *
     * @return the value of app_biz_log.biz_key
     *
     * @mbggenerated
     */
    public Long getBizKey() {
        return bizKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_log.biz_key
     *
     * @param bizKey the value for app_biz_log.biz_key
     *
     * @mbggenerated
     */
    public void setBizKey(Long bizKey) {
        this.bizKey = bizKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_log.state
     *
     * @return the value of app_biz_log.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_log.state
     *
     * @param state the value for app_biz_log.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_log.message
     *
     * @return the value of app_biz_log.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_log.message
     *
     * @param message the value for app_biz_log.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_log.creator
     *
     * @return the value of app_biz_log.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_log.creator
     *
     * @param creator the value for app_biz_log.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }
}