package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class AssetIncome {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.applier_name
     *
     * @mbggenerated
     */
    private String applierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.applier_id
     *
     * @mbggenerated
     */
    private String applierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.applier_area_type
     *
     * @mbggenerated
     */
    private String applierAreaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.applier_area_name
     *
     * @mbggenerated
     */
    private String applierAreaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.applier_area_id
     *
     * @mbggenerated
     */
    private Long applierAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.receiver_name
     *
     * @mbggenerated
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.receiver_workno
     *
     * @mbggenerated
     */
    private String receiverWorkno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.receiver_org_id
     *
     * @mbggenerated
     */
    private Long receiverOrgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.receiver_org_name
     *
     * @mbggenerated
     */
    private String receiverOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.po_no
     *
     * @mbggenerated
     */
    private String poNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_income.sign_type
     *
     * @mbggenerated
     */
    private String signType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.id
     *
     * @return the value of asset_income.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.id
     *
     * @param id the value for asset_income.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.gmt_create
     *
     * @return the value of asset_income.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.gmt_create
     *
     * @param gmtCreate the value for asset_income.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.gmt_modified
     *
     * @return the value of asset_income.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.gmt_modified
     *
     * @param gmtModified the value for asset_income.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.creator
     *
     * @return the value of asset_income.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.creator
     *
     * @param creator the value for asset_income.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.modifier
     *
     * @return the value of asset_income.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.modifier
     *
     * @param modifier the value for asset_income.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.is_deleted
     *
     * @return the value of asset_income.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.is_deleted
     *
     * @param isDeleted the value for asset_income.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.applier_name
     *
     * @return the value of asset_income.applier_name
     *
     * @mbggenerated
     */
    public String getApplierName() {
        return applierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.applier_name
     *
     * @param applierName the value for asset_income.applier_name
     *
     * @mbggenerated
     */
    public void setApplierName(String applierName) {
        this.applierName = applierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.applier_id
     *
     * @return the value of asset_income.applier_id
     *
     * @mbggenerated
     */
    public String getApplierId() {
        return applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.applier_id
     *
     * @param applierId the value for asset_income.applier_id
     *
     * @mbggenerated
     */
    public void setApplierId(String applierId) {
        this.applierId = applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.applier_area_type
     *
     * @return the value of asset_income.applier_area_type
     *
     * @mbggenerated
     */
    public String getApplierAreaType() {
        return applierAreaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.applier_area_type
     *
     * @param applierAreaType the value for asset_income.applier_area_type
     *
     * @mbggenerated
     */
    public void setApplierAreaType(String applierAreaType) {
        this.applierAreaType = applierAreaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.applier_area_name
     *
     * @return the value of asset_income.applier_area_name
     *
     * @mbggenerated
     */
    public String getApplierAreaName() {
        return applierAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.applier_area_name
     *
     * @param applierAreaName the value for asset_income.applier_area_name
     *
     * @mbggenerated
     */
    public void setApplierAreaName(String applierAreaName) {
        this.applierAreaName = applierAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.applier_area_id
     *
     * @return the value of asset_income.applier_area_id
     *
     * @mbggenerated
     */
    public Long getApplierAreaId() {
        return applierAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.applier_area_id
     *
     * @param applierAreaId the value for asset_income.applier_area_id
     *
     * @mbggenerated
     */
    public void setApplierAreaId(Long applierAreaId) {
        this.applierAreaId = applierAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.receiver_name
     *
     * @return the value of asset_income.receiver_name
     *
     * @mbggenerated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.receiver_name
     *
     * @param receiverName the value for asset_income.receiver_name
     *
     * @mbggenerated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.receiver_workno
     *
     * @return the value of asset_income.receiver_workno
     *
     * @mbggenerated
     */
    public String getReceiverWorkno() {
        return receiverWorkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.receiver_workno
     *
     * @param receiverWorkno the value for asset_income.receiver_workno
     *
     * @mbggenerated
     */
    public void setReceiverWorkno(String receiverWorkno) {
        this.receiverWorkno = receiverWorkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.receiver_org_id
     *
     * @return the value of asset_income.receiver_org_id
     *
     * @mbggenerated
     */
    public Long getReceiverOrgId() {
        return receiverOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.receiver_org_id
     *
     * @param receiverOrgId the value for asset_income.receiver_org_id
     *
     * @mbggenerated
     */
    public void setReceiverOrgId(Long receiverOrgId) {
        this.receiverOrgId = receiverOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.receiver_org_name
     *
     * @return the value of asset_income.receiver_org_name
     *
     * @mbggenerated
     */
    public String getReceiverOrgName() {
        return receiverOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.receiver_org_name
     *
     * @param receiverOrgName the value for asset_income.receiver_org_name
     *
     * @mbggenerated
     */
    public void setReceiverOrgName(String receiverOrgName) {
        this.receiverOrgName = receiverOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.type
     *
     * @return the value of asset_income.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.type
     *
     * @param type the value for asset_income.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.status
     *
     * @return the value of asset_income.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.status
     *
     * @param status the value for asset_income.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.po_no
     *
     * @return the value of asset_income.po_no
     *
     * @mbggenerated
     */
    public String getPoNo() {
        return poNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.po_no
     *
     * @param poNo the value for asset_income.po_no
     *
     * @mbggenerated
     */
    public void setPoNo(String poNo) {
        this.poNo = poNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.remark
     *
     * @return the value of asset_income.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.remark
     *
     * @param remark the value for asset_income.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_income.sign_type
     *
     * @return the value of asset_income.sign_type
     *
     * @mbggenerated
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_income.sign_type
     *
     * @param signType the value for asset_income.sign_type
     *
     * @mbggenerated
     */
    public void setSignType(String signType) {
        this.signType = signType;
    }
}