package com.taobao.cun.auge.dal.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AssetIncomeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public AssetIncomeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("is_deleted like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("is_deleted not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andApplierNameIsNull() {
            addCriterion("applier_name is null");
            return (Criteria) this;
        }

        public Criteria andApplierNameIsNotNull() {
            addCriterion("applier_name is not null");
            return (Criteria) this;
        }

        public Criteria andApplierNameEqualTo(String value) {
            addCriterion("applier_name =", value, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameNotEqualTo(String value) {
            addCriterion("applier_name <>", value, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameGreaterThan(String value) {
            addCriterion("applier_name >", value, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameGreaterThanOrEqualTo(String value) {
            addCriterion("applier_name >=", value, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameLessThan(String value) {
            addCriterion("applier_name <", value, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameLessThanOrEqualTo(String value) {
            addCriterion("applier_name <=", value, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameLike(String value) {
            addCriterion("applier_name like", value, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameNotLike(String value) {
            addCriterion("applier_name not like", value, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameIn(List<String> values) {
            addCriterion("applier_name in", values, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameNotIn(List<String> values) {
            addCriterion("applier_name not in", values, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameBetween(String value1, String value2) {
            addCriterion("applier_name between", value1, value2, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierNameNotBetween(String value1, String value2) {
            addCriterion("applier_name not between", value1, value2, "applierName");
            return (Criteria) this;
        }

        public Criteria andApplierIdIsNull() {
            addCriterion("applier_id is null");
            return (Criteria) this;
        }

        public Criteria andApplierIdIsNotNull() {
            addCriterion("applier_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplierIdEqualTo(String value) {
            addCriterion("applier_id =", value, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdNotEqualTo(String value) {
            addCriterion("applier_id <>", value, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdGreaterThan(String value) {
            addCriterion("applier_id >", value, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdGreaterThanOrEqualTo(String value) {
            addCriterion("applier_id >=", value, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdLessThan(String value) {
            addCriterion("applier_id <", value, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdLessThanOrEqualTo(String value) {
            addCriterion("applier_id <=", value, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdLike(String value) {
            addCriterion("applier_id like", value, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdNotLike(String value) {
            addCriterion("applier_id not like", value, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdIn(List<String> values) {
            addCriterion("applier_id in", values, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdNotIn(List<String> values) {
            addCriterion("applier_id not in", values, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdBetween(String value1, String value2) {
            addCriterion("applier_id between", value1, value2, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierIdNotBetween(String value1, String value2) {
            addCriterion("applier_id not between", value1, value2, "applierId");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeIsNull() {
            addCriterion("applier_area_type is null");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeIsNotNull() {
            addCriterion("applier_area_type is not null");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeEqualTo(String value) {
            addCriterion("applier_area_type =", value, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeNotEqualTo(String value) {
            addCriterion("applier_area_type <>", value, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeGreaterThan(String value) {
            addCriterion("applier_area_type >", value, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeGreaterThanOrEqualTo(String value) {
            addCriterion("applier_area_type >=", value, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeLessThan(String value) {
            addCriterion("applier_area_type <", value, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeLessThanOrEqualTo(String value) {
            addCriterion("applier_area_type <=", value, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeLike(String value) {
            addCriterion("applier_area_type like", value, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeNotLike(String value) {
            addCriterion("applier_area_type not like", value, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeIn(List<String> values) {
            addCriterion("applier_area_type in", values, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeNotIn(List<String> values) {
            addCriterion("applier_area_type not in", values, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeBetween(String value1, String value2) {
            addCriterion("applier_area_type between", value1, value2, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaTypeNotBetween(String value1, String value2) {
            addCriterion("applier_area_type not between", value1, value2, "applierAreaType");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameIsNull() {
            addCriterion("applier_area_name is null");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameIsNotNull() {
            addCriterion("applier_area_name is not null");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameEqualTo(String value) {
            addCriterion("applier_area_name =", value, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameNotEqualTo(String value) {
            addCriterion("applier_area_name <>", value, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameGreaterThan(String value) {
            addCriterion("applier_area_name >", value, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameGreaterThanOrEqualTo(String value) {
            addCriterion("applier_area_name >=", value, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameLessThan(String value) {
            addCriterion("applier_area_name <", value, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameLessThanOrEqualTo(String value) {
            addCriterion("applier_area_name <=", value, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameLike(String value) {
            addCriterion("applier_area_name like", value, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameNotLike(String value) {
            addCriterion("applier_area_name not like", value, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameIn(List<String> values) {
            addCriterion("applier_area_name in", values, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameNotIn(List<String> values) {
            addCriterion("applier_area_name not in", values, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameBetween(String value1, String value2) {
            addCriterion("applier_area_name between", value1, value2, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaNameNotBetween(String value1, String value2) {
            addCriterion("applier_area_name not between", value1, value2, "applierAreaName");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdIsNull() {
            addCriterion("applier_area_id is null");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdIsNotNull() {
            addCriterion("applier_area_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdEqualTo(Long value) {
            addCriterion("applier_area_id =", value, "applierAreaId");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdNotEqualTo(Long value) {
            addCriterion("applier_area_id <>", value, "applierAreaId");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdGreaterThan(Long value) {
            addCriterion("applier_area_id >", value, "applierAreaId");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("applier_area_id >=", value, "applierAreaId");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdLessThan(Long value) {
            addCriterion("applier_area_id <", value, "applierAreaId");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdLessThanOrEqualTo(Long value) {
            addCriterion("applier_area_id <=", value, "applierAreaId");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdIn(List<Long> values) {
            addCriterion("applier_area_id in", values, "applierAreaId");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdNotIn(List<Long> values) {
            addCriterion("applier_area_id not in", values, "applierAreaId");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdBetween(Long value1, Long value2) {
            addCriterion("applier_area_id between", value1, value2, "applierAreaId");
            return (Criteria) this;
        }

        public Criteria andApplierAreaIdNotBetween(Long value1, Long value2) {
            addCriterion("applier_area_id not between", value1, value2, "applierAreaId");
            return (Criteria) this;
        }

        public Criteria andReceiverNameIsNull() {
            addCriterion("receiver_name is null");
            return (Criteria) this;
        }

        public Criteria andReceiverNameIsNotNull() {
            addCriterion("receiver_name is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverNameEqualTo(String value) {
            addCriterion("receiver_name =", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameNotEqualTo(String value) {
            addCriterion("receiver_name <>", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameGreaterThan(String value) {
            addCriterion("receiver_name >", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameGreaterThanOrEqualTo(String value) {
            addCriterion("receiver_name >=", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameLessThan(String value) {
            addCriterion("receiver_name <", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameLessThanOrEqualTo(String value) {
            addCriterion("receiver_name <=", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameLike(String value) {
            addCriterion("receiver_name like", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameNotLike(String value) {
            addCriterion("receiver_name not like", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameIn(List<String> values) {
            addCriterion("receiver_name in", values, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameNotIn(List<String> values) {
            addCriterion("receiver_name not in", values, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameBetween(String value1, String value2) {
            addCriterion("receiver_name between", value1, value2, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameNotBetween(String value1, String value2) {
            addCriterion("receiver_name not between", value1, value2, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoIsNull() {
            addCriterion("receiver_workno is null");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoIsNotNull() {
            addCriterion("receiver_workno is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoEqualTo(String value) {
            addCriterion("receiver_workno =", value, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoNotEqualTo(String value) {
            addCriterion("receiver_workno <>", value, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoGreaterThan(String value) {
            addCriterion("receiver_workno >", value, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoGreaterThanOrEqualTo(String value) {
            addCriterion("receiver_workno >=", value, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoLessThan(String value) {
            addCriterion("receiver_workno <", value, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoLessThanOrEqualTo(String value) {
            addCriterion("receiver_workno <=", value, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoLike(String value) {
            addCriterion("receiver_workno like", value, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoNotLike(String value) {
            addCriterion("receiver_workno not like", value, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoIn(List<String> values) {
            addCriterion("receiver_workno in", values, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoNotIn(List<String> values) {
            addCriterion("receiver_workno not in", values, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoBetween(String value1, String value2) {
            addCriterion("receiver_workno between", value1, value2, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverWorknoNotBetween(String value1, String value2) {
            addCriterion("receiver_workno not between", value1, value2, "receiverWorkno");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdIsNull() {
            addCriterion("receiver_org_id is null");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdIsNotNull() {
            addCriterion("receiver_org_id is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdEqualTo(Long value) {
            addCriterion("receiver_org_id =", value, "receiverOrgId");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdNotEqualTo(Long value) {
            addCriterion("receiver_org_id <>", value, "receiverOrgId");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdGreaterThan(Long value) {
            addCriterion("receiver_org_id >", value, "receiverOrgId");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdGreaterThanOrEqualTo(Long value) {
            addCriterion("receiver_org_id >=", value, "receiverOrgId");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdLessThan(Long value) {
            addCriterion("receiver_org_id <", value, "receiverOrgId");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdLessThanOrEqualTo(Long value) {
            addCriterion("receiver_org_id <=", value, "receiverOrgId");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdIn(List<Long> values) {
            addCriterion("receiver_org_id in", values, "receiverOrgId");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdNotIn(List<Long> values) {
            addCriterion("receiver_org_id not in", values, "receiverOrgId");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdBetween(Long value1, Long value2) {
            addCriterion("receiver_org_id between", value1, value2, "receiverOrgId");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgIdNotBetween(Long value1, Long value2) {
            addCriterion("receiver_org_id not between", value1, value2, "receiverOrgId");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameIsNull() {
            addCriterion("receiver_org_name is null");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameIsNotNull() {
            addCriterion("receiver_org_name is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameEqualTo(String value) {
            addCriterion("receiver_org_name =", value, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameNotEqualTo(String value) {
            addCriterion("receiver_org_name <>", value, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameGreaterThan(String value) {
            addCriterion("receiver_org_name >", value, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameGreaterThanOrEqualTo(String value) {
            addCriterion("receiver_org_name >=", value, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameLessThan(String value) {
            addCriterion("receiver_org_name <", value, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameLessThanOrEqualTo(String value) {
            addCriterion("receiver_org_name <=", value, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameLike(String value) {
            addCriterion("receiver_org_name like", value, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameNotLike(String value) {
            addCriterion("receiver_org_name not like", value, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameIn(List<String> values) {
            addCriterion("receiver_org_name in", values, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameNotIn(List<String> values) {
            addCriterion("receiver_org_name not in", values, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameBetween(String value1, String value2) {
            addCriterion("receiver_org_name between", value1, value2, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andReceiverOrgNameNotBetween(String value1, String value2) {
            addCriterion("receiver_org_name not between", value1, value2, "receiverOrgName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPoNoIsNull() {
            addCriterion("po_no is null");
            return (Criteria) this;
        }

        public Criteria andPoNoIsNotNull() {
            addCriterion("po_no is not null");
            return (Criteria) this;
        }

        public Criteria andPoNoEqualTo(String value) {
            addCriterion("po_no =", value, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoNotEqualTo(String value) {
            addCriterion("po_no <>", value, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoGreaterThan(String value) {
            addCriterion("po_no >", value, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoGreaterThanOrEqualTo(String value) {
            addCriterion("po_no >=", value, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoLessThan(String value) {
            addCriterion("po_no <", value, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoLessThanOrEqualTo(String value) {
            addCriterion("po_no <=", value, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoLike(String value) {
            addCriterion("po_no like", value, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoNotLike(String value) {
            addCriterion("po_no not like", value, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoIn(List<String> values) {
            addCriterion("po_no in", values, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoNotIn(List<String> values) {
            addCriterion("po_no not in", values, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoBetween(String value1, String value2) {
            addCriterion("po_no between", value1, value2, "poNo");
            return (Criteria) this;
        }

        public Criteria andPoNoNotBetween(String value1, String value2) {
            addCriterion("po_no not between", value1, value2, "poNo");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asset_income
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asset_income
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}