package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class CuntaoAssetFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.apply_org
     *
     * @mbggenerated
     */
    private String applyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.apply_org_desc
     *
     * @mbggenerated
     */
    private String applyOrgDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.applier
     *
     * @mbggenerated
     */
    private String applier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.applier_no
     *
     * @mbggenerated
     */
    private String applierNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.receiver
     *
     * @mbggenerated
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.asset_owner
     *
     * @mbggenerated
     */
    private String assetOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.plan_receive_time
     *
     * @mbggenerated
     */
    private Date planReceiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.apply_status
     *
     * @mbggenerated
     */
    private String applyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.purchase_status
     *
     * @mbggenerated
     */
    private String purchaseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.receive_address
     *
     * @mbggenerated
     */
    private String receiveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.asset_situation
     *
     * @mbggenerated
     */
    private String assetSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.apply_time
     *
     * @mbggenerated
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_asset_flow.asset_owner_no
     *
     * @mbggenerated
     */
    private String assetOwnerNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.id
     *
     * @return the value of cuntao_asset_flow.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.id
     *
     * @param id the value for cuntao_asset_flow.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.gmt_create
     *
     * @return the value of cuntao_asset_flow.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.gmt_create
     *
     * @param gmtCreate the value for cuntao_asset_flow.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.gmt_modified
     *
     * @return the value of cuntao_asset_flow.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.gmt_modified
     *
     * @param gmtModified the value for cuntao_asset_flow.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.is_deleted
     *
     * @return the value of cuntao_asset_flow.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.is_deleted
     *
     * @param isDeleted the value for cuntao_asset_flow.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.creator
     *
     * @return the value of cuntao_asset_flow.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.creator
     *
     * @param creator the value for cuntao_asset_flow.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.modifier
     *
     * @return the value of cuntao_asset_flow.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.modifier
     *
     * @param modifier the value for cuntao_asset_flow.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.apply_org
     *
     * @return the value of cuntao_asset_flow.apply_org
     *
     * @mbggenerated
     */
    public String getApplyOrg() {
        return applyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.apply_org
     *
     * @param applyOrg the value for cuntao_asset_flow.apply_org
     *
     * @mbggenerated
     */
    public void setApplyOrg(String applyOrg) {
        this.applyOrg = applyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.apply_org_desc
     *
     * @return the value of cuntao_asset_flow.apply_org_desc
     *
     * @mbggenerated
     */
    public String getApplyOrgDesc() {
        return applyOrgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.apply_org_desc
     *
     * @param applyOrgDesc the value for cuntao_asset_flow.apply_org_desc
     *
     * @mbggenerated
     */
    public void setApplyOrgDesc(String applyOrgDesc) {
        this.applyOrgDesc = applyOrgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.applier
     *
     * @return the value of cuntao_asset_flow.applier
     *
     * @mbggenerated
     */
    public String getApplier() {
        return applier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.applier
     *
     * @param applier the value for cuntao_asset_flow.applier
     *
     * @mbggenerated
     */
    public void setApplier(String applier) {
        this.applier = applier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.applier_no
     *
     * @return the value of cuntao_asset_flow.applier_no
     *
     * @mbggenerated
     */
    public String getApplierNo() {
        return applierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.applier_no
     *
     * @param applierNo the value for cuntao_asset_flow.applier_no
     *
     * @mbggenerated
     */
    public void setApplierNo(String applierNo) {
        this.applierNo = applierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.receiver
     *
     * @return the value of cuntao_asset_flow.receiver
     *
     * @mbggenerated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.receiver
     *
     * @param receiver the value for cuntao_asset_flow.receiver
     *
     * @mbggenerated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.mobile
     *
     * @return the value of cuntao_asset_flow.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.mobile
     *
     * @param mobile the value for cuntao_asset_flow.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.asset_owner
     *
     * @return the value of cuntao_asset_flow.asset_owner
     *
     * @mbggenerated
     */
    public String getAssetOwner() {
        return assetOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.asset_owner
     *
     * @param assetOwner the value for cuntao_asset_flow.asset_owner
     *
     * @mbggenerated
     */
    public void setAssetOwner(String assetOwner) {
        this.assetOwner = assetOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.plan_receive_time
     *
     * @return the value of cuntao_asset_flow.plan_receive_time
     *
     * @mbggenerated
     */
    public Date getPlanReceiveTime() {
        return planReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.plan_receive_time
     *
     * @param planReceiveTime the value for cuntao_asset_flow.plan_receive_time
     *
     * @mbggenerated
     */
    public void setPlanReceiveTime(Date planReceiveTime) {
        this.planReceiveTime = planReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.apply_status
     *
     * @return the value of cuntao_asset_flow.apply_status
     *
     * @mbggenerated
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.apply_status
     *
     * @param applyStatus the value for cuntao_asset_flow.apply_status
     *
     * @mbggenerated
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.purchase_status
     *
     * @return the value of cuntao_asset_flow.purchase_status
     *
     * @mbggenerated
     */
    public String getPurchaseStatus() {
        return purchaseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.purchase_status
     *
     * @param purchaseStatus the value for cuntao_asset_flow.purchase_status
     *
     * @mbggenerated
     */
    public void setPurchaseStatus(String purchaseStatus) {
        this.purchaseStatus = purchaseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.receive_address
     *
     * @return the value of cuntao_asset_flow.receive_address
     *
     * @mbggenerated
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.receive_address
     *
     * @param receiveAddress the value for cuntao_asset_flow.receive_address
     *
     * @mbggenerated
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.remark
     *
     * @return the value of cuntao_asset_flow.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.remark
     *
     * @param remark the value for cuntao_asset_flow.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.asset_situation
     *
     * @return the value of cuntao_asset_flow.asset_situation
     *
     * @mbggenerated
     */
    public String getAssetSituation() {
        return assetSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.asset_situation
     *
     * @param assetSituation the value for cuntao_asset_flow.asset_situation
     *
     * @mbggenerated
     */
    public void setAssetSituation(String assetSituation) {
        this.assetSituation = assetSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.apply_time
     *
     * @return the value of cuntao_asset_flow.apply_time
     *
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.apply_time
     *
     * @param applyTime the value for cuntao_asset_flow.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_asset_flow.asset_owner_no
     *
     * @return the value of cuntao_asset_flow.asset_owner_no
     *
     * @mbggenerated
     */
    public String getAssetOwnerNo() {
        return assetOwnerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_asset_flow.asset_owner_no
     *
     * @param assetOwnerNo the value for cuntao_asset_flow.asset_owner_no
     *
     * @mbggenerated
     */
    public void setAssetOwnerNo(String assetOwnerNo) {
        this.assetOwnerNo = assetOwnerNo;
    }
}