package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class CuntaoInvoiceQualification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_invoice_qualification.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_invoice_qualification.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_invoice_qualification.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_invoice_qualification.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_invoice_qualification.taobao_user_id
     *
     * @mbggenerated
     */
    private Long taobaoUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_invoice_qualification.invoice_file
     *
     * @mbggenerated
     */
    private String invoiceFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_invoice_qualification.invoice_file_type
     *
     * @mbggenerated
     */
    private String invoiceFileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_invoice_qualification.effective_start_time
     *
     * @mbggenerated
     */
    private Date effectiveStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_invoice_qualification.effective_end_time
     *
     * @mbggenerated
     */
    private Date effectiveEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_invoice_qualification.upload_time
     *
     * @mbggenerated
     */
    private Date uploadTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_invoice_qualification.id
     *
     * @return the value of cuntao_invoice_qualification.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_invoice_qualification.id
     *
     * @param id the value for cuntao_invoice_qualification.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_invoice_qualification.gmt_create
     *
     * @return the value of cuntao_invoice_qualification.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_invoice_qualification.gmt_create
     *
     * @param gmtCreate the value for cuntao_invoice_qualification.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_invoice_qualification.gmt_modified
     *
     * @return the value of cuntao_invoice_qualification.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_invoice_qualification.gmt_modified
     *
     * @param gmtModified the value for cuntao_invoice_qualification.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_invoice_qualification.is_deleted
     *
     * @return the value of cuntao_invoice_qualification.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_invoice_qualification.is_deleted
     *
     * @param isDeleted the value for cuntao_invoice_qualification.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_invoice_qualification.taobao_user_id
     *
     * @return the value of cuntao_invoice_qualification.taobao_user_id
     *
     * @mbggenerated
     */
    public Long getTaobaoUserId() {
        return taobaoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_invoice_qualification.taobao_user_id
     *
     * @param taobaoUserId the value for cuntao_invoice_qualification.taobao_user_id
     *
     * @mbggenerated
     */
    public void setTaobaoUserId(Long taobaoUserId) {
        this.taobaoUserId = taobaoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_invoice_qualification.invoice_file
     *
     * @return the value of cuntao_invoice_qualification.invoice_file
     *
     * @mbggenerated
     */
    public String getInvoiceFile() {
        return invoiceFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_invoice_qualification.invoice_file
     *
     * @param invoiceFile the value for cuntao_invoice_qualification.invoice_file
     *
     * @mbggenerated
     */
    public void setInvoiceFile(String invoiceFile) {
        this.invoiceFile = invoiceFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_invoice_qualification.invoice_file_type
     *
     * @return the value of cuntao_invoice_qualification.invoice_file_type
     *
     * @mbggenerated
     */
    public String getInvoiceFileType() {
        return invoiceFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_invoice_qualification.invoice_file_type
     *
     * @param invoiceFileType the value for cuntao_invoice_qualification.invoice_file_type
     *
     * @mbggenerated
     */
    public void setInvoiceFileType(String invoiceFileType) {
        this.invoiceFileType = invoiceFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_invoice_qualification.effective_start_time
     *
     * @return the value of cuntao_invoice_qualification.effective_start_time
     *
     * @mbggenerated
     */
    public Date getEffectiveStartTime() {
        return effectiveStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_invoice_qualification.effective_start_time
     *
     * @param effectiveStartTime the value for cuntao_invoice_qualification.effective_start_time
     *
     * @mbggenerated
     */
    public void setEffectiveStartTime(Date effectiveStartTime) {
        this.effectiveStartTime = effectiveStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_invoice_qualification.effective_end_time
     *
     * @return the value of cuntao_invoice_qualification.effective_end_time
     *
     * @mbggenerated
     */
    public Date getEffectiveEndTime() {
        return effectiveEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_invoice_qualification.effective_end_time
     *
     * @param effectiveEndTime the value for cuntao_invoice_qualification.effective_end_time
     *
     * @mbggenerated
     */
    public void setEffectiveEndTime(Date effectiveEndTime) {
        this.effectiveEndTime = effectiveEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_invoice_qualification.upload_time
     *
     * @return the value of cuntao_invoice_qualification.upload_time
     *
     * @mbggenerated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_invoice_qualification.upload_time
     *
     * @param uploadTime the value for cuntao_invoice_qualification.upload_time
     *
     * @mbggenerated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }
}