package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class CuntaoLifecycleTransition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.taobao_user_id
     *
     * @mbggenerated
     */
    private Long taobaoUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.station_id
     *
     * @mbggenerated
     */
    private Long stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.new_state
     *
     * @mbggenerated
     */
    private String newState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.old_state
     *
     * @mbggenerated
     */
    private String oldState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.spend_time
     *
     * @mbggenerated
     */
    private Long spendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.change_time
     *
     * @mbggenerated
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.biz_type
     *
     * @mbggenerated
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.biz_primary_key
     *
     * @mbggenerated
     */
    private Long bizPrimaryKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.is_main_state_transition
     *
     * @mbggenerated
     */
    private String isMainStateTransition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.parent_state
     *
     * @mbggenerated
     */
    private String parentState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_lifecycle_transition.sub_biz_type
     *
     * @mbggenerated
     */
    private String subBizType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.id
     *
     * @return the value of cuntao_lifecycle_transition.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.id
     *
     * @param id the value for cuntao_lifecycle_transition.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.gmt_create
     *
     * @return the value of cuntao_lifecycle_transition.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.gmt_create
     *
     * @param gmtCreate the value for cuntao_lifecycle_transition.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.gmt_modified
     *
     * @return the value of cuntao_lifecycle_transition.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.gmt_modified
     *
     * @param gmtModified the value for cuntao_lifecycle_transition.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.creator
     *
     * @return the value of cuntao_lifecycle_transition.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.creator
     *
     * @param creator the value for cuntao_lifecycle_transition.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.modifier
     *
     * @return the value of cuntao_lifecycle_transition.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.modifier
     *
     * @param modifier the value for cuntao_lifecycle_transition.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.is_deleted
     *
     * @return the value of cuntao_lifecycle_transition.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.is_deleted
     *
     * @param isDeleted the value for cuntao_lifecycle_transition.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.taobao_user_id
     *
     * @return the value of cuntao_lifecycle_transition.taobao_user_id
     *
     * @mbggenerated
     */
    public Long getTaobaoUserId() {
        return taobaoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.taobao_user_id
     *
     * @param taobaoUserId the value for cuntao_lifecycle_transition.taobao_user_id
     *
     * @mbggenerated
     */
    public void setTaobaoUserId(Long taobaoUserId) {
        this.taobaoUserId = taobaoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.station_id
     *
     * @return the value of cuntao_lifecycle_transition.station_id
     *
     * @mbggenerated
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.station_id
     *
     * @param stationId the value for cuntao_lifecycle_transition.station_id
     *
     * @mbggenerated
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.new_state
     *
     * @return the value of cuntao_lifecycle_transition.new_state
     *
     * @mbggenerated
     */
    public String getNewState() {
        return newState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.new_state
     *
     * @param newState the value for cuntao_lifecycle_transition.new_state
     *
     * @mbggenerated
     */
    public void setNewState(String newState) {
        this.newState = newState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.old_state
     *
     * @return the value of cuntao_lifecycle_transition.old_state
     *
     * @mbggenerated
     */
    public String getOldState() {
        return oldState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.old_state
     *
     * @param oldState the value for cuntao_lifecycle_transition.old_state
     *
     * @mbggenerated
     */
    public void setOldState(String oldState) {
        this.oldState = oldState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.spend_time
     *
     * @return the value of cuntao_lifecycle_transition.spend_time
     *
     * @mbggenerated
     */
    public Long getSpendTime() {
        return spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.spend_time
     *
     * @param spendTime the value for cuntao_lifecycle_transition.spend_time
     *
     * @mbggenerated
     */
    public void setSpendTime(Long spendTime) {
        this.spendTime = spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.change_time
     *
     * @return the value of cuntao_lifecycle_transition.change_time
     *
     * @mbggenerated
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.change_time
     *
     * @param changeTime the value for cuntao_lifecycle_transition.change_time
     *
     * @mbggenerated
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.biz_type
     *
     * @return the value of cuntao_lifecycle_transition.biz_type
     *
     * @mbggenerated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.biz_type
     *
     * @param bizType the value for cuntao_lifecycle_transition.biz_type
     *
     * @mbggenerated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.user_type
     *
     * @return the value of cuntao_lifecycle_transition.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.user_type
     *
     * @param userType the value for cuntao_lifecycle_transition.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.biz_primary_key
     *
     * @return the value of cuntao_lifecycle_transition.biz_primary_key
     *
     * @mbggenerated
     */
    public Long getBizPrimaryKey() {
        return bizPrimaryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.biz_primary_key
     *
     * @param bizPrimaryKey the value for cuntao_lifecycle_transition.biz_primary_key
     *
     * @mbggenerated
     */
    public void setBizPrimaryKey(Long bizPrimaryKey) {
        this.bizPrimaryKey = bizPrimaryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.version
     *
     * @return the value of cuntao_lifecycle_transition.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.version
     *
     * @param version the value for cuntao_lifecycle_transition.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.is_main_state_transition
     *
     * @return the value of cuntao_lifecycle_transition.is_main_state_transition
     *
     * @mbggenerated
     */
    public String getIsMainStateTransition() {
        return isMainStateTransition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.is_main_state_transition
     *
     * @param isMainStateTransition the value for cuntao_lifecycle_transition.is_main_state_transition
     *
     * @mbggenerated
     */
    public void setIsMainStateTransition(String isMainStateTransition) {
        this.isMainStateTransition = isMainStateTransition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.parent_state
     *
     * @return the value of cuntao_lifecycle_transition.parent_state
     *
     * @mbggenerated
     */
    public String getParentState() {
        return parentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.parent_state
     *
     * @param parentState the value for cuntao_lifecycle_transition.parent_state
     *
     * @mbggenerated
     */
    public void setParentState(String parentState) {
        this.parentState = parentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_lifecycle_transition.sub_biz_type
     *
     * @return the value of cuntao_lifecycle_transition.sub_biz_type
     *
     * @mbggenerated
     */
    public String getSubBizType() {
        return subBizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_lifecycle_transition.sub_biz_type
     *
     * @param subBizType the value for cuntao_lifecycle_transition.sub_biz_type
     *
     * @mbggenerated
     */
    public void setSubBizType(String subBizType) {
        this.subBizType = subBizType;
    }
}