package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class CuntaoUserRoleLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_user_role_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_user_role_log.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_user_role_log.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_user_role_log.old_role
     *
     * @mbggenerated
     */
    private String oldRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_user_role_log.new_role
     *
     * @mbggenerated
     */
    private String newRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_user_role_log.org_id
     *
     * @mbggenerated
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_user_role_log.login_id
     *
     * @mbggenerated
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_user_role_log.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cuntao_user_role_log.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_user_role_log.id
     *
     * @return the value of cuntao_user_role_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_user_role_log.id
     *
     * @param id the value for cuntao_user_role_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_user_role_log.gmt_create
     *
     * @return the value of cuntao_user_role_log.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_user_role_log.gmt_create
     *
     * @param gmtCreate the value for cuntao_user_role_log.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_user_role_log.gmt_modified
     *
     * @return the value of cuntao_user_role_log.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_user_role_log.gmt_modified
     *
     * @param gmtModified the value for cuntao_user_role_log.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_user_role_log.old_role
     *
     * @return the value of cuntao_user_role_log.old_role
     *
     * @mbggenerated
     */
    public String getOldRole() {
        return oldRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_user_role_log.old_role
     *
     * @param oldRole the value for cuntao_user_role_log.old_role
     *
     * @mbggenerated
     */
    public void setOldRole(String oldRole) {
        this.oldRole = oldRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_user_role_log.new_role
     *
     * @return the value of cuntao_user_role_log.new_role
     *
     * @mbggenerated
     */
    public String getNewRole() {
        return newRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_user_role_log.new_role
     *
     * @param newRole the value for cuntao_user_role_log.new_role
     *
     * @mbggenerated
     */
    public void setNewRole(String newRole) {
        this.newRole = newRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_user_role_log.org_id
     *
     * @return the value of cuntao_user_role_log.org_id
     *
     * @mbggenerated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_user_role_log.org_id
     *
     * @param orgId the value for cuntao_user_role_log.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_user_role_log.login_id
     *
     * @return the value of cuntao_user_role_log.login_id
     *
     * @mbggenerated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_user_role_log.login_id
     *
     * @param loginId the value for cuntao_user_role_log.login_id
     *
     * @mbggenerated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_user_role_log.creator
     *
     * @return the value of cuntao_user_role_log.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_user_role_log.creator
     *
     * @param creator the value for cuntao_user_role_log.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cuntao_user_role_log.modifier
     *
     * @return the value of cuntao_user_role_log.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cuntao_user_role_log.modifier
     *
     * @param modifier the value for cuntao_user_role_log.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
}