package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class FenceEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.template_id
     *
     * @mbggenerated
     */
    private Long templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.station_id
     *
     * @mbggenerated
     */
    private Long stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.cainiao_station_id
     *
     * @mbggenerated
     */
    private Long cainiaoStationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.default_check
     *
     * @mbggenerated
     */
    private String defaultCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.limit_commodity
     *
     * @mbggenerated
     */
    private String limitCommodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.commodity
     *
     * @mbggenerated
     */
    private String commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.range_enable
     *
     * @mbggenerated
     */
    private String rangeEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.distance
     *
     * @mbggenerated
     */
    private Integer distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.text_match_type
     *
     * @mbggenerated
     */
    private String textMatchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.text_match_value
     *
     * @mbggenerated
     */
    private String textMatchValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.division
     *
     * @mbggenerated
     */
    private String division;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fence_entity.division_value
     *
     * @mbggenerated
     */
    private String divisionValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.id
     *
     * @return the value of fence_entity.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.id
     *
     * @param id the value for fence_entity.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.gmt_create
     *
     * @return the value of fence_entity.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.gmt_create
     *
     * @param gmtCreate the value for fence_entity.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.gmt_modified
     *
     * @return the value of fence_entity.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.gmt_modified
     *
     * @param gmtModified the value for fence_entity.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.creator
     *
     * @return the value of fence_entity.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.creator
     *
     * @param creator the value for fence_entity.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.modifier
     *
     * @return the value of fence_entity.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.modifier
     *
     * @param modifier the value for fence_entity.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.is_deleted
     *
     * @return the value of fence_entity.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.is_deleted
     *
     * @param isDeleted the value for fence_entity.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.template_id
     *
     * @return the value of fence_entity.template_id
     *
     * @mbggenerated
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.template_id
     *
     * @param templateId the value for fence_entity.template_id
     *
     * @mbggenerated
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.station_id
     *
     * @return the value of fence_entity.station_id
     *
     * @mbggenerated
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.station_id
     *
     * @param stationId the value for fence_entity.station_id
     *
     * @mbggenerated
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.cainiao_station_id
     *
     * @return the value of fence_entity.cainiao_station_id
     *
     * @mbggenerated
     */
    public Long getCainiaoStationId() {
        return cainiaoStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.cainiao_station_id
     *
     * @param cainiaoStationId the value for fence_entity.cainiao_station_id
     *
     * @mbggenerated
     */
    public void setCainiaoStationId(Long cainiaoStationId) {
        this.cainiaoStationId = cainiaoStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.name
     *
     * @return the value of fence_entity.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.name
     *
     * @param name the value for fence_entity.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.type
     *
     * @return the value of fence_entity.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.type
     *
     * @param type the value for fence_entity.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.user_type
     *
     * @return the value of fence_entity.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.user_type
     *
     * @param userType the value for fence_entity.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.state
     *
     * @return the value of fence_entity.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.state
     *
     * @param state the value for fence_entity.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.default_check
     *
     * @return the value of fence_entity.default_check
     *
     * @mbggenerated
     */
    public String getDefaultCheck() {
        return defaultCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.default_check
     *
     * @param defaultCheck the value for fence_entity.default_check
     *
     * @mbggenerated
     */
    public void setDefaultCheck(String defaultCheck) {
        this.defaultCheck = defaultCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.limit_commodity
     *
     * @return the value of fence_entity.limit_commodity
     *
     * @mbggenerated
     */
    public String getLimitCommodity() {
        return limitCommodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.limit_commodity
     *
     * @param limitCommodity the value for fence_entity.limit_commodity
     *
     * @mbggenerated
     */
    public void setLimitCommodity(String limitCommodity) {
        this.limitCommodity = limitCommodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.commodity
     *
     * @return the value of fence_entity.commodity
     *
     * @mbggenerated
     */
    public String getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.commodity
     *
     * @param commodity the value for fence_entity.commodity
     *
     * @mbggenerated
     */
    public void setCommodity(String commodity) {
        this.commodity = commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.category
     *
     * @return the value of fence_entity.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.category
     *
     * @param category the value for fence_entity.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.range_enable
     *
     * @return the value of fence_entity.range_enable
     *
     * @mbggenerated
     */
    public String getRangeEnable() {
        return rangeEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.range_enable
     *
     * @param rangeEnable the value for fence_entity.range_enable
     *
     * @mbggenerated
     */
    public void setRangeEnable(String rangeEnable) {
        this.rangeEnable = rangeEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.distance
     *
     * @return the value of fence_entity.distance
     *
     * @mbggenerated
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.distance
     *
     * @param distance the value for fence_entity.distance
     *
     * @mbggenerated
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.text_match_type
     *
     * @return the value of fence_entity.text_match_type
     *
     * @mbggenerated
     */
    public String getTextMatchType() {
        return textMatchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.text_match_type
     *
     * @param textMatchType the value for fence_entity.text_match_type
     *
     * @mbggenerated
     */
    public void setTextMatchType(String textMatchType) {
        this.textMatchType = textMatchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.text_match_value
     *
     * @return the value of fence_entity.text_match_value
     *
     * @mbggenerated
     */
    public String getTextMatchValue() {
        return textMatchValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.text_match_value
     *
     * @param textMatchValue the value for fence_entity.text_match_value
     *
     * @mbggenerated
     */
    public void setTextMatchValue(String textMatchValue) {
        this.textMatchValue = textMatchValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.division
     *
     * @return the value of fence_entity.division
     *
     * @mbggenerated
     */
    public String getDivision() {
        return division;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.division
     *
     * @param division the value for fence_entity.division
     *
     * @mbggenerated
     */
    public void setDivision(String division) {
        this.division = division;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fence_entity.division_value
     *
     * @return the value of fence_entity.division_value
     *
     * @mbggenerated
     */
    public String getDivisionValue() {
        return divisionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fence_entity.division_value
     *
     * @param divisionValue the value for fence_entity.division_value
     *
     * @mbggenerated
     */
    public void setDivisionValue(String divisionValue) {
        this.divisionValue = divisionValue;
    }
}