package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class ShutDownStationApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shut_down_station_apply.id
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shut_down_station_apply.gmt_create
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shut_down_station_apply.gmt_modified
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shut_down_station_apply.creator
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shut_down_station_apply.modifier
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shut_down_station_apply.station_id
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    private Long stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shut_down_station_apply.reason
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shut_down_station_apply.applier_id
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    private String applierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shut_down_station_apply.apply_time
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    private Date applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shut_down_station_apply.is_deleted
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shut_down_station_apply.id
     *
     * @return the value of shut_down_station_apply.id
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shut_down_station_apply.id
     *
     * @param id the value for shut_down_station_apply.id
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shut_down_station_apply.gmt_create
     *
     * @return the value of shut_down_station_apply.gmt_create
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shut_down_station_apply.gmt_create
     *
     * @param gmtCreate the value for shut_down_station_apply.gmt_create
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shut_down_station_apply.gmt_modified
     *
     * @return the value of shut_down_station_apply.gmt_modified
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shut_down_station_apply.gmt_modified
     *
     * @param gmtModified the value for shut_down_station_apply.gmt_modified
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shut_down_station_apply.creator
     *
     * @return the value of shut_down_station_apply.creator
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shut_down_station_apply.creator
     *
     * @param creator the value for shut_down_station_apply.creator
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shut_down_station_apply.modifier
     *
     * @return the value of shut_down_station_apply.modifier
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shut_down_station_apply.modifier
     *
     * @param modifier the value for shut_down_station_apply.modifier
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shut_down_station_apply.station_id
     *
     * @return the value of shut_down_station_apply.station_id
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shut_down_station_apply.station_id
     *
     * @param stationId the value for shut_down_station_apply.station_id
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shut_down_station_apply.reason
     *
     * @return the value of shut_down_station_apply.reason
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shut_down_station_apply.reason
     *
     * @param reason the value for shut_down_station_apply.reason
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shut_down_station_apply.applier_id
     *
     * @return the value of shut_down_station_apply.applier_id
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public String getApplierId() {
        return applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shut_down_station_apply.applier_id
     *
     * @param applierId the value for shut_down_station_apply.applier_id
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public void setApplierId(String applierId) {
        this.applierId = applierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shut_down_station_apply.apply_time
     *
     * @return the value of shut_down_station_apply.apply_time
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shut_down_station_apply.apply_time
     *
     * @param applyTime the value for shut_down_station_apply.apply_time
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shut_down_station_apply.is_deleted
     *
     * @return the value of shut_down_station_apply.is_deleted
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shut_down_station_apply.is_deleted
     *
     * @param isDeleted the value for shut_down_station_apply.is_deleted
     *
     * @mbggenerated Thu Aug 25 15:34:43 GMT+08:00 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
}