package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class Station {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.gmt_create
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.gmt_modified
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.creater
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.modifier
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.name
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.description
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.alipay_account
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String alipayAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.taobao_nick
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String taobaoNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.state
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.is_deleted
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.province
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.city
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.county
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.town
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.province_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String provinceDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.city_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String cityDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.county_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String countyDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.town_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String townDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.address
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.apply_org
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private Long applyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.taobao_user_id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private Long taobaoUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.station_num
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String stationNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.lng
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.lat
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.village
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String village;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.village_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String villageDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.covered
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String covered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.products
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String products;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.logistics_state
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String logisticsState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.format
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.area_type
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String areaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.manager_id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.provider_id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private Long providerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.feature
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.status
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.fixed_type
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    private String fixedType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.id
     *
     * @return the value of station.id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.id
     *
     * @param id the value for station.id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.gmt_create
     *
     * @return the value of station.gmt_create
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.gmt_create
     *
     * @param gmtCreate the value for station.gmt_create
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.gmt_modified
     *
     * @return the value of station.gmt_modified
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.gmt_modified
     *
     * @param gmtModified the value for station.gmt_modified
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.creater
     *
     * @return the value of station.creater
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.creater
     *
     * @param creater the value for station.creater
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.modifier
     *
     * @return the value of station.modifier
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.modifier
     *
     * @param modifier the value for station.modifier
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.name
     *
     * @return the value of station.name
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.name
     *
     * @param name the value for station.name
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.description
     *
     * @return the value of station.description
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.description
     *
     * @param description the value for station.description
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.alipay_account
     *
     * @return the value of station.alipay_account
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getAlipayAccount() {
        return alipayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.alipay_account
     *
     * @param alipayAccount the value for station.alipay_account
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setAlipayAccount(String alipayAccount) {
        this.alipayAccount = alipayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.taobao_nick
     *
     * @return the value of station.taobao_nick
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getTaobaoNick() {
        return taobaoNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.taobao_nick
     *
     * @param taobaoNick the value for station.taobao_nick
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setTaobaoNick(String taobaoNick) {
        this.taobaoNick = taobaoNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.state
     *
     * @return the value of station.state
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.state
     *
     * @param state the value for station.state
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.is_deleted
     *
     * @return the value of station.is_deleted
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.is_deleted
     *
     * @param isDeleted the value for station.is_deleted
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.province
     *
     * @return the value of station.province
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.province
     *
     * @param province the value for station.province
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.city
     *
     * @return the value of station.city
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.city
     *
     * @param city the value for station.city
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.county
     *
     * @return the value of station.county
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.county
     *
     * @param county the value for station.county
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.town
     *
     * @return the value of station.town
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.town
     *
     * @param town the value for station.town
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setTown(String town) {
        this.town = town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.province_detail
     *
     * @return the value of station.province_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getProvinceDetail() {
        return provinceDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.province_detail
     *
     * @param provinceDetail the value for station.province_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setProvinceDetail(String provinceDetail) {
        this.provinceDetail = provinceDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.city_detail
     *
     * @return the value of station.city_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getCityDetail() {
        return cityDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.city_detail
     *
     * @param cityDetail the value for station.city_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setCityDetail(String cityDetail) {
        this.cityDetail = cityDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.county_detail
     *
     * @return the value of station.county_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getCountyDetail() {
        return countyDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.county_detail
     *
     * @param countyDetail the value for station.county_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setCountyDetail(String countyDetail) {
        this.countyDetail = countyDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.town_detail
     *
     * @return the value of station.town_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getTownDetail() {
        return townDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.town_detail
     *
     * @param townDetail the value for station.town_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setTownDetail(String townDetail) {
        this.townDetail = townDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.address
     *
     * @return the value of station.address
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.address
     *
     * @param address the value for station.address
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.apply_org
     *
     * @return the value of station.apply_org
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public Long getApplyOrg() {
        return applyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.apply_org
     *
     * @param applyOrg the value for station.apply_org
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setApplyOrg(Long applyOrg) {
        this.applyOrg = applyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.taobao_user_id
     *
     * @return the value of station.taobao_user_id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public Long getTaobaoUserId() {
        return taobaoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.taobao_user_id
     *
     * @param taobaoUserId the value for station.taobao_user_id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setTaobaoUserId(Long taobaoUserId) {
        this.taobaoUserId = taobaoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.station_num
     *
     * @return the value of station.station_num
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getStationNum() {
        return stationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.station_num
     *
     * @param stationNum the value for station.station_num
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setStationNum(String stationNum) {
        this.stationNum = stationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.lng
     *
     * @return the value of station.lng
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.lng
     *
     * @param lng the value for station.lng
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setLng(String lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.lat
     *
     * @return the value of station.lat
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.lat
     *
     * @param lat the value for station.lat
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setLat(String lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.village
     *
     * @return the value of station.village
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getVillage() {
        return village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.village
     *
     * @param village the value for station.village
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setVillage(String village) {
        this.village = village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.village_detail
     *
     * @return the value of station.village_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getVillageDetail() {
        return villageDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.village_detail
     *
     * @param villageDetail the value for station.village_detail
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setVillageDetail(String villageDetail) {
        this.villageDetail = villageDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.covered
     *
     * @return the value of station.covered
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getCovered() {
        return covered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.covered
     *
     * @param covered the value for station.covered
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setCovered(String covered) {
        this.covered = covered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.products
     *
     * @return the value of station.products
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getProducts() {
        return products;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.products
     *
     * @param products the value for station.products
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setProducts(String products) {
        this.products = products;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.logistics_state
     *
     * @return the value of station.logistics_state
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getLogisticsState() {
        return logisticsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.logistics_state
     *
     * @param logisticsState the value for station.logistics_state
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setLogisticsState(String logisticsState) {
        this.logisticsState = logisticsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.format
     *
     * @return the value of station.format
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.format
     *
     * @param format the value for station.format
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setFormat(String format) {
        this.format = format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.area_type
     *
     * @return the value of station.area_type
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.area_type
     *
     * @param areaType the value for station.area_type
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.manager_id
     *
     * @return the value of station.manager_id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.manager_id
     *
     * @param managerId the value for station.manager_id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.provider_id
     *
     * @return the value of station.provider_id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.provider_id
     *
     * @param providerId the value for station.provider_id
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.feature
     *
     * @return the value of station.feature
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.feature
     *
     * @param feature the value for station.feature
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setFeature(String feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.status
     *
     * @return the value of station.status
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.status
     *
     * @param status the value for station.status
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.fixed_type
     *
     * @return the value of station.fixed_type
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public String getFixedType() {
        return fixedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.fixed_type
     *
     * @param fixedType the value for station.fixed_type
     *
     * @mbggenerated Mon May 30 17:14:20 CST 2016
     */
    public void setFixedType(String fixedType) {
        this.fixedType = fixedType;
    }
}