package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class StationNumConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.seq_num
     *
     * @mbggenerated
     */
    private String seqNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_num_config.province_ab
     *
     * @mbggenerated
     */
    private String provinceAb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.id
     *
     * @return the value of station_num_config.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.id
     *
     * @param id the value for station_num_config.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.gmt_create
     *
     * @return the value of station_num_config.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.gmt_create
     *
     * @param gmtCreate the value for station_num_config.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.gmt_modified
     *
     * @return the value of station_num_config.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.gmt_modified
     *
     * @param gmtModified the value for station_num_config.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.creater
     *
     * @return the value of station_num_config.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.creater
     *
     * @param creater the value for station_num_config.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.modifier
     *
     * @return the value of station_num_config.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.modifier
     *
     * @param modifier the value for station_num_config.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.is_deleted
     *
     * @return the value of station_num_config.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.is_deleted
     *
     * @param isDeleted the value for station_num_config.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.province_name
     *
     * @return the value of station_num_config.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.province_name
     *
     * @param provinceName the value for station_num_config.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.province_code
     *
     * @return the value of station_num_config.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.province_code
     *
     * @param provinceCode the value for station_num_config.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.type
     *
     * @return the value of station_num_config.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.type
     *
     * @param type the value for station_num_config.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.seq_num
     *
     * @return the value of station_num_config.seq_num
     *
     * @mbggenerated
     */
    public String getSeqNum() {
        return seqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.seq_num
     *
     * @param seqNum the value for station_num_config.seq_num
     *
     * @mbggenerated
     */
    public void setSeqNum(String seqNum) {
        this.seqNum = seqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_num_config.province_ab
     *
     * @return the value of station_num_config.province_ab
     *
     * @mbggenerated
     */
    public String getProvinceAb() {
        return provinceAb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_num_config.province_ab
     *
     * @param provinceAb the value for station_num_config.province_ab
     *
     * @mbggenerated
     */
    public void setProvinceAb(String provinceAb) {
        this.provinceAb = provinceAb;
    }
}