package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class StationManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.station_id
     *
     * @mbggenerated
     */
    private String stationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.worker_type
     *
     * @mbggenerated
     */
    private String workerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.worker_id
     *
     * @mbggenerated
     */
    private String workerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.worker_name
     *
     * @mbggenerated
     */
    private String workerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.extra
     *
     * @mbggenerated
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_manager.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.id
     *
     * @return the value of station_manager.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.id
     *
     * @param id the value for station_manager.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.gmt_create
     *
     * @return the value of station_manager.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.gmt_create
     *
     * @param gmtCreate the value for station_manager.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.gmt_modified
     *
     * @return the value of station_manager.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.gmt_modified
     *
     * @param gmtModified the value for station_manager.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.creator
     *
     * @return the value of station_manager.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.creator
     *
     * @param creator the value for station_manager.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.modifier
     *
     * @return the value of station_manager.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.modifier
     *
     * @param modifier the value for station_manager.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.station_id
     *
     * @return the value of station_manager.station_id
     *
     * @mbggenerated
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.station_id
     *
     * @param stationId the value for station_manager.station_id
     *
     * @mbggenerated
     */
    public void setStationId(String stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.worker_type
     *
     * @return the value of station_manager.worker_type
     *
     * @mbggenerated
     */
    public String getWorkerType() {
        return workerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.worker_type
     *
     * @param workerType the value for station_manager.worker_type
     *
     * @mbggenerated
     */
    public void setWorkerType(String workerType) {
        this.workerType = workerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.worker_id
     *
     * @return the value of station_manager.worker_id
     *
     * @mbggenerated
     */
    public String getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.worker_id
     *
     * @param workerId the value for station_manager.worker_id
     *
     * @mbggenerated
     */
    public void setWorkerId(String workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.worker_name
     *
     * @return the value of station_manager.worker_name
     *
     * @mbggenerated
     */
    public String getWorkerName() {
        return workerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.worker_name
     *
     * @param workerName the value for station_manager.worker_name
     *
     * @mbggenerated
     */
    public void setWorkerName(String workerName) {
        this.workerName = workerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.extra
     *
     * @return the value of station_manager.extra
     *
     * @mbggenerated
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.extra
     *
     * @param extra the value for station_manager.extra
     *
     * @mbggenerated
     */
    public void setExtra(String extra) {
        this.extra = extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_manager.is_deleted
     *
     * @return the value of station_manager.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_manager.is_deleted
     *
     * @param isDeleted the value for station_manager.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
}