package com.taobao.cun.auge.dal.domain;

import java.util.Date;

public class TownLevelRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town_level_rule.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town_level_rule.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town_level_rule.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town_level_rule.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town_level_rule.level_rule
     *
     * @mbggenerated
     */
    private String levelRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town_level_rule.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town_level_rule.id
     *
     * @return the value of town_level_rule.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town_level_rule.id
     *
     * @param id the value for town_level_rule.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town_level_rule.gmt_create
     *
     * @return the value of town_level_rule.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town_level_rule.gmt_create
     *
     * @param gmtCreate the value for town_level_rule.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town_level_rule.gmt_modified
     *
     * @return the value of town_level_rule.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town_level_rule.gmt_modified
     *
     * @param gmtModified the value for town_level_rule.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town_level_rule.level
     *
     * @return the value of town_level_rule.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town_level_rule.level
     *
     * @param level the value for town_level_rule.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town_level_rule.level_rule
     *
     * @return the value of town_level_rule.level_rule
     *
     * @mbggenerated
     */
    public String getLevelRule() {
        return levelRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town_level_rule.level_rule
     *
     * @param levelRule the value for town_level_rule.level_rule
     *
     * @mbggenerated
     */
    public void setLevelRule(String levelRule) {
        this.levelRule = levelRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town_level_rule.area_code
     *
     * @return the value of town_level_rule.area_code
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town_level_rule.area_code
     *
     * @param areaCode the value for town_level_rule.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }
}